# Aider Configuration
# This file configures Aider to use instructions from the .agents directory

# System message that will be shown to Aider
system-message: |
  Project-wide instructions are located at ./.agents/instructions.md
  
  Instructions for additional workflows are included in ./.agents/
  
  Before starting any task, please make sure that you check to see if any of the instructions in .agents/ corresponds with the task you are being asked to complete.

# Auto-commit settings
auto-commits: true
dirty-commits: false

# Git settings
git: true